[tools]
node = "latest"
rust = "latest"

[tasks.download]
run = [
    "echo Downloading files...",
    "gh release download --repo firstforest/daily-task-logger --pattern *.vsix",
]

[tasks.install]
run = "node scripts/install-vsix.js"

[tasks.release]
run = ["npm version patch", "git push origin main", "git push --tags"]
